// Generated by scripts/build-draft-dataset.mjs — do not edit by hand.
// Which Draft Room seasons exist in public/draft/, newest first.

export type DraftSeasonMeta = {
  season: number;
  scoutSeasons: number[];
  players: number;
  scoutGames: number;
  kb: number;
};

export const DRAFT_SEASONS: DraftSeasonMeta[] = [
  {
    "season": 2025,
    "scoutSeasons": [
      2022,
      2023,
      2024
    ],
    "players": 192,
    "scoutGames": 5759,
    "kb": 446
  },
  {
    "season": 2024,
    "scoutSeasons": [
      2021,
      2022,
      2023
    ],
    "players": 192,
    "scoutGames": 5544,
    "kb": 432
  },
  {
    "season": 2023,
    "scoutSeasons": [
      2020,
      2021,
      2022
    ],
    "players": 192,
    "scoutGames": 5564,
    "kb": 433
  }
];
