// GENERATED by scripts/build-lesson-dataset.mjs — do not edit by hand.
//
// Numbers the lesson prose quotes, derived from the same rows the lessons
// seed. scripts/verify-answer-keys.mjs re-checks each one against the
// database. Import from here rather than typing a number into a lesson.

export const FACTS = {
  "rows": 1221,
  "gamesTable": 1135,
  "players": 20,
  "seasons": [
    2022,
    2023,
    2024,
    2025,
    2026
  ],
  "latest": {
    "season": 2026,
    "week": 3
  },
  "teams": 18,
  "playerTeamPairs": 26,
  "movers": 5,
  "possibleGames": 71,
  "maxGame": {
    "pts": 55.4,
    "games": [
      {
        "player": "Ja'Marr Chase",
        "season": 2024,
        "week": 10
      },
      {
        "player": "Jahmyr Gibbs",
        "season": 2025,
        "week": 12
      }
    ]
  },
  "over25": 282,
  "boom30": 145,
  "gamesPlayed": {
    "Justin Jefferson": 64,
    "Patrick Mahomes": 66,
    "Saquon Barkley": 65,
    "Josh Allen": 68,
    "Davante Adams": 65,
    "Ja'Marr Chase": 64,
    "Travis Kelce": 68,
    "A.J. Brown": 63,
    "Jalen Hurts": 66,
    "Amon-Ra St. Brown": 69,
    "Lamar Jackson": 61,
    "Tyreek Hill": 54,
    "Christian McCaffrey": 57,
    "Derrick Henry": 70,
    "CeeDee Lamb": 65,
    "George Kittle": 60,
    "Puka Nacua": 45,
    "Bijan Robinson": 54,
    "Sam LaPorta": 45,
    "Jahmyr Gibbs": 52
  },
  "seasonPpg": {
    "A.J. Brown": [
      [
        2022,
        17.6
      ],
      [
        2023,
        17
      ],
      [
        2024,
        16.7
      ],
      [
        2025,
        14.7
      ],
      [
        2026,
        5.6
      ]
    ],
    "Amon-Ra St. Brown": [
      [
        2022,
        16.7
      ],
      [
        2023,
        20.7
      ],
      [
        2024,
        18.6
      ],
      [
        2025,
        19.1
      ],
      [
        2026,
        25.3
      ]
    ],
    "Bijan Robinson": [
      [
        2023,
        14.5
      ],
      [
        2024,
        20.1
      ],
      [
        2025,
        21.8
      ],
      [
        2026,
        25.9
      ]
    ],
    "CeeDee Lamb": [
      [
        2022,
        17.7
      ],
      [
        2023,
        23.7
      ],
      [
        2024,
        17.6
      ],
      [
        2025,
        15.5
      ],
      [
        2026,
        23.6
      ]
    ],
    "Christian McCaffrey": [
      [
        2022,
        21
      ],
      [
        2023,
        24.5
      ],
      [
        2024,
        11.9
      ],
      [
        2025,
        24.5
      ],
      [
        2026,
        19.3
      ]
    ],
    "Davante Adams": [
      [
        2022,
        19.7
      ],
      [
        2023,
        15.6
      ],
      [
        2024,
        17.2
      ],
      [
        2025,
        15.9
      ],
      [
        2026,
        21.9
      ]
    ],
    "Derrick Henry": [
      [
        2022,
        18.9
      ],
      [
        2023,
        14.5
      ],
      [
        2024,
        19.8
      ],
      [
        2025,
        16.4
      ],
      [
        2026,
        25
      ]
    ],
    "George Kittle": [
      [
        2022,
        13.4
      ],
      [
        2023,
        12.7
      ],
      [
        2024,
        15.8
      ],
      [
        2025,
        14.7
      ],
      [
        2026,
        15.8
      ]
    ],
    "Ja'Marr Chase": [
      [
        2022,
        20.2
      ],
      [
        2023,
        16.4
      ],
      [
        2024,
        23.7
      ],
      [
        2025,
        19.6
      ],
      [
        2026,
        18.2
      ]
    ],
    "Jahmyr Gibbs": [
      [
        2023,
        16.1
      ],
      [
        2024,
        21.3
      ],
      [
        2025,
        21.6
      ],
      [
        2026,
        32.8
      ]
    ],
    "Jalen Hurts": [
      [
        2022,
        25.2
      ],
      [
        2023,
        21
      ],
      [
        2024,
        21
      ],
      [
        2025,
        18.8
      ],
      [
        2026,
        17.8
      ]
    ],
    "Josh Allen": [
      [
        2022,
        24.7
      ],
      [
        2023,
        23.1
      ],
      [
        2024,
        23.7
      ],
      [
        2025,
        22.8
      ],
      [
        2026,
        31.3
      ]
    ],
    "Justin Jefferson": [
      [
        2022,
        21.7
      ],
      [
        2023,
        20.2
      ],
      [
        2024,
        18.7
      ],
      [
        2025,
        11.9
      ],
      [
        2026,
        15
      ]
    ],
    "Lamar Jackson": [
      [
        2022,
        19.7
      ],
      [
        2023,
        20.7
      ],
      [
        2024,
        25.3
      ],
      [
        2025,
        16.5
      ],
      [
        2026,
        20.1
      ]
    ],
    "Patrick Mahomes": [
      [
        2022,
        24.6
      ],
      [
        2023,
        17.5
      ],
      [
        2024,
        17.7
      ],
      [
        2025,
        20.4
      ],
      [
        2026,
        22.2
      ]
    ],
    "Puka Nacua": [
      [
        2023,
        17.6
      ],
      [
        2024,
        18.8
      ],
      [
        2025,
        23.4
      ],
      [
        2026,
        12.4
      ]
    ],
    "Sam LaPorta": [
      [
        2023,
        14.1
      ],
      [
        2024,
        10.9
      ],
      [
        2025,
        11.9
      ],
      [
        2026,
        11.5
      ]
    ],
    "Saquon Barkley": [
      [
        2022,
        17.8
      ],
      [
        2023,
        15.9
      ],
      [
        2024,
        22.2
      ],
      [
        2025,
        14.5
      ],
      [
        2026,
        7
      ]
    ],
    "Travis Kelce": [
      [
        2022,
        18.6
      ],
      [
        2023,
        14.6
      ],
      [
        2024,
        12.2
      ],
      [
        2025,
        11.4
      ],
      [
        2026,
        16.4
      ]
    ],
    "Tyreek Hill": [
      [
        2022,
        20.1
      ],
      [
        2023,
        23.5
      ],
      [
        2024,
        12.8
      ],
      [
        2025,
        13.4
      ]
    ]
  },
  "league": {
    "season": 2024,
    "wireWeek": 10,
    "drafted": 10,
    "undrafted": 10,
    "wireRows": 8,
    "leader": {
      "team": "Goal Line Gang",
      "pts": 744.7
    },
    "undraftedByPoints": [
      "Lamar Jackson",
      "Josh Allen",
      "Derrick Henry",
      "Jalen Hurts",
      "Patrick Mahomes",
      "Davante Adams",
      "George Kittle",
      "Puka Nacua",
      "Travis Kelce",
      "Sam LaPorta"
    ],
    "topRiser": {
      "player": "Khalil Herbert",
      "trend": 32.6
    },
    "topRostered": {
      "player": "Ja'Marr Chase",
      "pts": 403
    }
  }
} as const;
