// GENERATED by scripts/build-player-headshots.mjs - do not edit by hand.
//
// Headshot URL, current team and position for each lesson player, from
// nflverse-data's weekly stats release. The URLs are the NFL's own image CDN
// exactly as nflverse lists them; components/headshot.tsx hotlinks them and
// never proxies them. "Current" is the newest season with a stat line.
//
// Source and licence: lib/data-source.ts

export type PlayerHeadshot = {
  url: string;
  /** Team in the newest season seen, which may differ from the lesson rows. */
  team: string;
  position: string;
  season: number;
};

export const PLAYER_HEADSHOTS: Record<string, PlayerHeadshot> = {
  "A.J. Brown": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/qfhvjyssf0lwsh0kienp","team":"NE","position":"WR","season":2026},
  "Amon-Ra St. Brown": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/fd8nwhm6pvxfyzphzl6i","team":"DET","position":"WR","season":2026},
  "Bijan Robinson": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/esii5yb8yn9edboi4mlq","team":"ATL","position":"RB","season":2026},
  "CeeDee Lamb": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/mbblzwtynxr15ovzkevi","team":"DAL","position":"WR","season":2026},
  "Christian McCaffrey": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/st82s2ytyzanatcmkqck","team":"SF","position":"RB","season":2026},
  "Davante Adams": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/tdzluk4xau3arxqk9zsl","team":"LA","position":"WR","season":2026},
  "Derrick Henry": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/tm79x0iknqg6hms3ypyt","team":"BAL","position":"RB","season":2026},
  "George Kittle": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/vkicdglglkyukgyxtmpx","team":"SF","position":"TE","season":2026},
  "Ja'Marr Chase": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/qya3dtjb5kgofcuj2tuw","team":"CIN","position":"WR","season":2026},
  "Jahmyr Gibbs": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/cursejnmmp1i9hnxihkj","team":"DET","position":"RB","season":2026},
  "Jalen Hurts": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/xow5yvxjeqa6witmofmp","team":"PHI","position":"QB","season":2026},
  "Josh Allen": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/mjwbioajzldkq1vzoz2d","team":"BUF","position":"QB","season":2026},
  "Justin Jefferson": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/htjevkugzk6ietrjysny","team":"MIN","position":"WR","season":2026},
  "Lamar Jackson": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/eno6s5qzl9grbfbfwhoa","team":"BAL","position":"QB","season":2026},
  "Patrick Mahomes": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/wdckwtob1lybvkmxnf7p","team":"KC","position":"QB","season":2026},
  "Puka Nacua": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/ipy6qw7hdygdfc8k86ba","team":"LA","position":"WR","season":2026},
  "Sam LaPorta": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/wxlk7ysg2nfq6h6ntdcu","team":"DET","position":"TE","season":2026},
  "Saquon Barkley": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/qcayrzjpura2zydszonh","team":"PHI","position":"RB","season":2026},
  "Travis Kelce": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/dpxovcfku6ud2aohgf6a","team":"KC","position":"TE","season":2026},
  "Tyreek Hill": {"url":"https://static.www.nfl.com/image/upload/f_auto,q_auto/league/gg73gnfivrn80oyqwazl","team":"MIA","position":"WR","season":2025},
};
