// GENERATED by scripts/build-team-colors.mjs — do not edit by hand.
//
// Official team colours and logo URLs from nflverse-data (teams release).
// Colours go on every table; logos go on scoreboards only, and are hotlinked
// from the source nflverse lists (ESPN's CDN), never served from our domain.
//
// Source and licence: lib/data-source.ts

export type TeamColor = {
  abbr: string;
  name: string;
  nick: string;
  primary: string;
  secondary: string | null;
  /** ESPN-hosted crest, or null when nflverse lists none. */
  logo: string | null;
};

export const TEAM_COLORS: TeamColor[] = [
  {"abbr":"ARI","name":"Arizona Cardinals","nick":"Cardinals","primary":"#97233F","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/ari.png"},
  {"abbr":"ATL","name":"Atlanta Falcons","nick":"Falcons","primary":"#A71930","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/atl.png"},
  {"abbr":"BAL","name":"Baltimore Ravens","nick":"Ravens","primary":"#241773","secondary":"#9E7C0C","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/bal.png"},
  {"abbr":"BUF","name":"Buffalo Bills","nick":"Bills","primary":"#00338D","secondary":"#C60C30","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/buf.png"},
  {"abbr":"CAR","name":"Carolina Panthers","nick":"Panthers","primary":"#0085CA","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500-dark/car.png"},
  {"abbr":"CHI","name":"Chicago Bears","nick":"Bears","primary":"#0B162A","secondary":"#E64100","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/chi.png"},
  {"abbr":"CIN","name":"Cincinnati Bengals","nick":"Bengals","primary":"#FB4F14","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/cin.png"},
  {"abbr":"CLE","name":"Cleveland Browns","nick":"Browns","primary":"#FF3C00","secondary":"#311D00","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/cle.png"},
  {"abbr":"DAL","name":"Dallas Cowboys","nick":"Cowboys","primary":"#002244","secondary":"#B0B7BC","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/dal.png"},
  {"abbr":"DEN","name":"Denver Broncos","nick":"Broncos","primary":"#002244","secondary":"#FB4F14","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/den.png"},
  {"abbr":"DET","name":"Detroit Lions","nick":"Lions","primary":"#0076B6","secondary":"#B0B7BC","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/det.png"},
  {"abbr":"GB","name":"Green Bay Packers","nick":"Packers","primary":"#203731","secondary":"#FFB612","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/gb.png"},
  {"abbr":"HOU","name":"Houston Texans","nick":"Texans","primary":"#03202F","secondary":"#A71930","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"},
  {"abbr":"IND","name":"Indianapolis Colts","nick":"Colts","primary":"#002C5F","secondary":"#A5ACAF","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/ind.png"},
  {"abbr":"JAX","name":"Jacksonville Jaguars","nick":"Jaguars","primary":"#006778","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/jax.png"},
  {"abbr":"KC","name":"Kansas City Chiefs","nick":"Chiefs","primary":"#E31837","secondary":"#FFB612","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/kc.png"},
  {"abbr":"LA","name":"Los Angeles Rams","nick":"Rams","primary":"#003594","secondary":"#FFD100","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"},
  {"abbr":"LAC","name":"Los Angeles Chargers","nick":"Chargers","primary":"#007BC7","secondary":"#FFC20E","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lac.png"},
  {"abbr":"LAR","name":"Los Angeles Rams","nick":"Rams","primary":"#003594","secondary":"#FFD100","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"},
  {"abbr":"LV","name":"Las Vegas Raiders","nick":"Raiders","primary":"#000000","secondary":"#A5ACAF","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lv.png"},
  {"abbr":"MIA","name":"Miami Dolphins","nick":"Dolphins","primary":"#008E97","secondary":"#F58220","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/mia.png"},
  {"abbr":"MIN","name":"Minnesota Vikings","nick":"Vikings","primary":"#4F2683","secondary":"#FFC62F","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/min.png"},
  {"abbr":"NE","name":"New England Patriots","nick":"Patriots","primary":"#002244","secondary":"#C60C30","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/ne.png"},
  {"abbr":"NO","name":"New Orleans Saints","nick":"Saints","primary":"#D3BC8D","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/no.png"},
  {"abbr":"NYG","name":"New York Giants","nick":"Giants","primary":"#0B2265","secondary":"#A71930","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png"},
  {"abbr":"NYJ","name":"New York Jets","nick":"Jets","primary":"#003F2D","secondary":"#000000","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png"},
  {"abbr":"OAK","name":"Oakland Raiders","nick":"Raiders","primary":"#000000","secondary":"#A5ACAF","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lv.png"},
  {"abbr":"PHI","name":"Philadelphia Eagles","nick":"Eagles","primary":"#004C54","secondary":"#A5ACAF","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/phi.png"},
  {"abbr":"PIT","name":"Pittsburgh Steelers","nick":"Steelers","primary":"#000000","secondary":"#FFB612","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/pit.png"},
  {"abbr":"SD","name":"San Diego Chargers","nick":"Chargers","primary":"#007BC7","secondary":"#FFC20E","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lac.png"},
  {"abbr":"SEA","name":"Seattle Seahawks","nick":"Seahawks","primary":"#002244","secondary":"#69BE28","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/sea.png"},
  {"abbr":"SF","name":"San Francisco 49ers","nick":"49ers","primary":"#AA0000","secondary":"#B3995D","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/sf.png"},
  {"abbr":"STL","name":"St. Louis Rams","nick":"Rams","primary":"#003594","secondary":"#FFD100","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png"},
  {"abbr":"TB","name":"Tampa Bay Buccaneers","nick":"Buccaneers","primary":"#A71930","secondary":"#322F2B","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/tb.png"},
  {"abbr":"TEN","name":"Tennessee Titans","nick":"Titans","primary":"#4495D2","secondary":"#D50A0A","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/ten.png"},
  {"abbr":"WAS","name":"Washington Commanders","nick":"Commanders","primary":"#5A1414","secondary":"#FFB612","logo":"https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png"},
];
