// GENERATED by scripts/build-team-colors.mjs — do not edit by hand.
//
// Official team colours from nflverse-data (teams release). Colours only:
// logos and wordmarks are trademarks and are deliberately not used anywhere
// in this product.
//
// Source and licence: lib/data-source.ts

export type TeamColor = {
  abbr: string;
  name: string;
  nick: string;
  primary: string;
  secondary: string | null;
};

export const TEAM_COLORS: TeamColor[] = [
  {"abbr":"ARI","name":"Arizona Cardinals","nick":"Cardinals","primary":"#97233F","secondary":"#000000"},
  {"abbr":"ATL","name":"Atlanta Falcons","nick":"Falcons","primary":"#A71930","secondary":"#000000"},
  {"abbr":"BAL","name":"Baltimore Ravens","nick":"Ravens","primary":"#241773","secondary":"#9E7C0C"},
  {"abbr":"BUF","name":"Buffalo Bills","nick":"Bills","primary":"#00338D","secondary":"#C60C30"},
  {"abbr":"CAR","name":"Carolina Panthers","nick":"Panthers","primary":"#0085CA","secondary":"#000000"},
  {"abbr":"CHI","name":"Chicago Bears","nick":"Bears","primary":"#0B162A","secondary":"#E64100"},
  {"abbr":"CIN","name":"Cincinnati Bengals","nick":"Bengals","primary":"#FB4F14","secondary":"#000000"},
  {"abbr":"CLE","name":"Cleveland Browns","nick":"Browns","primary":"#FF3C00","secondary":"#311D00"},
  {"abbr":"DAL","name":"Dallas Cowboys","nick":"Cowboys","primary":"#002244","secondary":"#B0B7BC"},
  {"abbr":"DEN","name":"Denver Broncos","nick":"Broncos","primary":"#002244","secondary":"#FB4F14"},
  {"abbr":"DET","name":"Detroit Lions","nick":"Lions","primary":"#0076B6","secondary":"#B0B7BC"},
  {"abbr":"GB","name":"Green Bay Packers","nick":"Packers","primary":"#203731","secondary":"#FFB612"},
  {"abbr":"HOU","name":"Houston Texans","nick":"Texans","primary":"#03202F","secondary":"#A71930"},
  {"abbr":"IND","name":"Indianapolis Colts","nick":"Colts","primary":"#002C5F","secondary":"#A5ACAF"},
  {"abbr":"JAX","name":"Jacksonville Jaguars","nick":"Jaguars","primary":"#006778","secondary":"#000000"},
  {"abbr":"KC","name":"Kansas City Chiefs","nick":"Chiefs","primary":"#E31837","secondary":"#FFB612"},
  {"abbr":"LA","name":"Los Angeles Rams","nick":"Rams","primary":"#003594","secondary":"#FFD100"},
  {"abbr":"LAC","name":"Los Angeles Chargers","nick":"Chargers","primary":"#007BC7","secondary":"#FFC20E"},
  {"abbr":"LAR","name":"Los Angeles Rams","nick":"Rams","primary":"#003594","secondary":"#FFD100"},
  {"abbr":"LV","name":"Las Vegas Raiders","nick":"Raiders","primary":"#000000","secondary":"#A5ACAF"},
  {"abbr":"MIA","name":"Miami Dolphins","nick":"Dolphins","primary":"#008E97","secondary":"#F58220"},
  {"abbr":"MIN","name":"Minnesota Vikings","nick":"Vikings","primary":"#4F2683","secondary":"#FFC62F"},
  {"abbr":"NE","name":"New England Patriots","nick":"Patriots","primary":"#002244","secondary":"#C60C30"},
  {"abbr":"NO","name":"New Orleans Saints","nick":"Saints","primary":"#D3BC8D","secondary":"#000000"},
  {"abbr":"NYG","name":"New York Giants","nick":"Giants","primary":"#0B2265","secondary":"#A71930"},
  {"abbr":"NYJ","name":"New York Jets","nick":"Jets","primary":"#003F2D","secondary":"#000000"},
  {"abbr":"OAK","name":"Oakland Raiders","nick":"Raiders","primary":"#000000","secondary":"#A5ACAF"},
  {"abbr":"PHI","name":"Philadelphia Eagles","nick":"Eagles","primary":"#004C54","secondary":"#A5ACAF"},
  {"abbr":"PIT","name":"Pittsburgh Steelers","nick":"Steelers","primary":"#000000","secondary":"#FFB612"},
  {"abbr":"SD","name":"San Diego Chargers","nick":"Chargers","primary":"#007BC7","secondary":"#FFC20E"},
  {"abbr":"SEA","name":"Seattle Seahawks","nick":"Seahawks","primary":"#002244","secondary":"#69BE28"},
  {"abbr":"SF","name":"San Francisco 49ers","nick":"49ers","primary":"#AA0000","secondary":"#B3995D"},
  {"abbr":"STL","name":"St. Louis Rams","nick":"Rams","primary":"#003594","secondary":"#FFD100"},
  {"abbr":"TB","name":"Tampa Bay Buccaneers","nick":"Buccaneers","primary":"#A71930","secondary":"#322F2B"},
  {"abbr":"TEN","name":"Tennessee Titans","nick":"Titans","primary":"#4495D2","secondary":"#D50A0A"},
  {"abbr":"WAS","name":"Washington Commanders","nick":"Commanders","primary":"#5A1414","secondary":"#FFB612"},
];
